POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "sessionType": "interval",
  "answersWrong": 0,
  "answersCorrect": 5,
  "sessionHistory": [
      { "answer": "perfect unison", "correctAnswer" : "perfect unison"},
      { "answer": "perfect unison", "correctAnswer" : "perfect unison"},
      { "answer": "perfect unison", "correctAnswer" : "perfect unison"},
      { "answer": "perfect unison", "correctAnswer" : "perfect unison"},
      { "answer": "perfect unison", "correctAnswer" : "perfect unison"}
    ]
}